name: my_all_projects
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  zoom_tap_animation: ^1.1.0
  flutter_bloc: ^8.1.5
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  equatable: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/bodoni/
    - assets/fonts/inter/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Bodoni
      fonts:
        - asset: assets/fonts/bodoni/BodoniFLF-Bold.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-BoldItalic.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/bodoni/BodoniFLF-Roman.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf